/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.google.gson.Gson;
import dao.ConnectionProvider;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import utility.BDUtility;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;
/**
 *
 * @author ASUS
 */
public class GenerateQr extends javax.swing.JFrame {

    /**
     * Creates new form GenerateQr
     */
    public GenerateQr() {
        initComponents();
// ImageIcon originalIcon = new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\AttendanceManagementSystemBD\\src\\utility\\images\\bck2.jpg");
//        int desiredWidth = 1182;
//        int desiredHeight = 501;
//
//        // Check if the image size matches the desired dimensions
//        if (originalIcon.getIconWidth() == desiredWidth && originalIcon.getIconHeight() == desiredHeight) {
//            // Use the original image
//            ImageIcon scaledIcon = originalIcon;
//            JLabel imageLabel = new JLabel(scaledIcon);
//            imageLabel.setBounds(0, 0, desiredWidth, desiredHeight);
//            this.add(imageLabel);
//        } else {
//            // Scale the image to the desired dimensions
//            Image scaledImage = originalIcon.getImage().getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
//            ImageIcon scaledIcon = new ImageIcon(scaledImage);
//            JLabel imageLabel = new JLabel(scaledIcon);
//            imageLabel.setBounds(0, 0, desiredWidth, desiredHeight);
//            this.add(imageLabel);
//            System.out.println("Image has been resized to fit the desired dimensions of " + desiredWidth + "x" + desiredHeight);
//        }
//
//        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.setSize(1182, 501);
//        this.setLayout(null);
//        this.setVisible(true);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        btnSavaQr = new javax.swing.JButton();
        btnSaveQrAt = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnExt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExt.setText("x");
        btnExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Generate User QR");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Gender", "Email", "Contact", "Address", "State", "Country", "Registration Id"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        btnSavaQr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSavaQr.setText("Save QR");
        btnSavaQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavaQrActionPerformed(evt);
            }
        });

        btnSaveQrAt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveQrAt.setText("Save QR At");
        btnSaveQrAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQrAtActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(487, 487, 487)
                        .addComponent(btnExt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSavaQr)
                .addGap(18, 18, 18)
                .addComponent(btnSaveQrAt)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExt)
                    .addComponent(jLabel1))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavaQr)
                    .addComponent(btnSaveQrAt))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExtActionPerformed

    private void btnSavaQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavaQrActionPerformed
        try {
    if (out == null) {
        JOptionPane.showMessageDialog(this, "No QR Generated!");
        return; // Add return statement correctly here
    }

    String defaultDir = BDUtility.getPath("qrCodes"); // Use assignment operator
    File directory = new File(defaultDir);

    if (!directory.exists()) {
        directory.mkdirs(); 
    }

    File defaultFile = new File(directory, email + ".jpg"); // Use assignment operator

    try {
        java.nio.file.Files.write(defaultFile.toPath(), out.toByteArray());
        JOptionPane.showMessageDialog(null, "QR Code saved successfully!");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error saving QR Code.", "Error", JOptionPane.ERROR_MESSAGE); // Fixed method call
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Something went wrong.", "Error", JOptionPane.ERROR_MESSAGE); // Add a catch block for outer try
}

    }//GEN-LAST:event_btnSavaQrActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
      
    }//GEN-LAST:event_lblImageMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       
DefaultTableModel model = (DefaultTableModel) userTable.getModel();

    try {
        Connection connection = ConnectionProvider.getCon();
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery("select * from userdetails");

        while (resultSet.next()) {
            model.addRow(new Object[] {
                resultSet.getString("id"),
                resultSet.getString("name"),
                resultSet.getString("gender"),
                resultSet.getString("email"),
                resultSet.getString("contact"),
                resultSet.getString("address"),
                resultSet.getString("state"),
                resultSet.getString("country"),
                resultSet.getString("uniqueregid") // Assuming 'uniqueregid' instead of 'uni'
            });
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Something went wrong.");
    }



    }//GEN-LAST:event_formComponentShown
ByteArrayOutputStream out = null;

String email = null;


    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
          int index = userTable.getSelectedRow();
    TableModel model = userTable.getModel();

    String id = model.getValueAt(index, 0).toString();
    String name = model.getValueAt(index, 1).toString();
    email = model.getValueAt(index, 3).toString(); // Use assignment operator
    String registrationId = model.getValueAt(index, 8).toString();

    Map<String, String> data = new HashMap<>();
    data.put("id", id);
    data.put("name", name);
    data.put("email", email);
    data.put("registrationId", registrationId);

    Gson gson = new Gson();
    String jsonData = gson.toJson(data); // Use assignment operator

    out = QRCode.from(jsonData).withSize(322, 286).to(ImageType.PNG).stream();

    try {
        byte[] imageData = out.toByteArray();
        ImageIcon icon = new ImageIcon(imageData);
        lblImage.setIcon(icon);
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_userTableMouseClicked

    private void btnSaveQrAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQrAtActionPerformed
        try {
    if (out == null) {
        JOptionPane.showMessageDialog(this, "No QR Generated!");
        return; // Ensure return statement is properly placed
    }

    JFileChooser fileChooser = new JFileChooser(); // Use assignment operator
    fileChooser.setDialogTitle("Save QR Code at");
    fileChooser.setSelectedFile(new File(email + ".png")); // Fixed the file name to use correct quotes

    int userSelection = fileChooser.showSaveDialog(this); // Fixed method name

    if (userSelection == JFileChooser.APPROVE_OPTION) { // Fixed enum usage
        File fileToSave = fileChooser.getSelectedFile();

        try {
            java.nio.file.Files.write(fileToSave.toPath(), out.toByteArray());
            JOptionPane.showMessageDialog(this, "QR Code saved successfully!"); // Fixed typo
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error saving QR Code.", "Error", JOptionPane.ERROR_MESSAGE); // Fixed method call
        }
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Something went wrong."); // Consider adding a more informative message
}

    }//GEN-LAST:event_btnSaveQrAtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateQr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateQr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExt;
    private javax.swing.JButton btnSavaQr;
    private javax.swing.JButton btnSaveQrAt;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
